"use client";

import { useState } from "react";
import { Mail, MessageCircle, ShieldCheck } from "lucide-react";
import LegalFooter from "@/components/legal-footer";
import { Button, Input, Logo } from "@/components/ui";

export default function ContactPage() {
  const [sent,setSent]=useState(false);
  return <div className="min-h-screen bg-cream"><header className="container-page flex h-24 items-center"><Logo/></header><main className="container-page pb-24 pt-8"><div className="mx-auto grid max-w-5xl gap-6 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-[32px] bg-forest p-8 text-white sm:p-10"><Mail className="text-light"/><p className="mt-8 text-xs font-bold uppercase tracking-widest text-light">Fale com a gente</p><h1 className="mt-4 font-display text-5xl">Contato e suporte</h1><p className="mt-5 leading-7 text-white/60">Dúvidas sobre sua conta, assinatura, reembolso ou privacidade podem ser enviadas pelo formulário.</p><div className="mt-10 rounded-2xl bg-white/10 p-5"><p className="text-xs text-white/40">E-mail de suporte</p><a className="mt-1 block font-bold" href="mailto:suporte@recomecar.app">suporte@recomecar.app</a></div></div><div className="rounded-[32px] bg-white p-8 sm:p-10">{sent?<div className="grid min-h-96 place-items-center text-center"><div><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-mist text-forest"><ShieldCheck/></span><h2 className="mt-6 font-display text-4xl">Mensagem preparada.</h2><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-ink/55">Este MVP ainda não possui serviço de envio. Escreva diretamente para suporte@recomecar.app com os dados informados.</p><Button className="mt-6" onClick={()=>setSent(false)}>Enviar outra mensagem</Button></div></div>:<form className="grid gap-5" onSubmit={(e)=>{e.preventDefault();setSent(true)}}><div><MessageCircle className="text-forest"/><h2 className="mt-4 font-display text-4xl">Como podemos ajudar?</h2></div><Input required label="Nome" placeholder="Seu nome"/><Input required type="email" label="E-mail" placeholder="voce@email.com"/><label className="grid gap-2 text-sm font-bold text-ink/80">Assunto<select required className="focus-ring rounded-2xl border border-ink/10 bg-white px-4 py-3.5"><option>Suporte geral</option><option>Cancelamento ou reembolso</option><option>Privacidade e LGPD</option><option>Assinatura</option></select></label><label className="grid gap-2 text-sm font-bold text-ink/80">Mensagem<textarea required rows={6} className="focus-ring resize-none rounded-2xl border border-ink/10 p-4 font-medium"/></label><Button type="submit">Preparar mensagem</Button></form>}</div></div></main><LegalFooter/></div>;
}
