import LegalPage from "@/components/legal-page";

export default function PrivacyPage() {
  return <LegalPage eyebrow="Privacidade e LGPD" title="Política de Privacidade" intro="Explicamos de forma clara quais dados tratamos, por que precisamos deles e como você pode exercer seus direitos." sections={[
    {title:"Quem controla seus dados",paragraphs:["O Recomeçar é o controlador dos dados pessoais tratados na plataforma. Para este MVP, o canal de privacidade é suporte@recomecar.app. Os dados cadastrais definitivos da empresa serão publicados antes do início da operação comercial."]},
    {title:"Dados que podemos coletar",items:["Nome, e-mail e dados de autenticação.","Estado civil e informações fornecidas no onboarding.","Renda, despesas, dívidas, parcelas, metas e valores guardados.","Dados de utilização, dispositivo, registros técnicos e preferências de cookies.","Mensagens enviadas ao suporte e histórico de solicitações."]},
    {title:"Por que usamos esses dados",items:["Criar e manter sua conta.","Calcular diagnósticos, projeções, metas e planos personalizados.","Executar pagamento, acesso e suporte quando esses recursos forem ativados.","Proteger a plataforma, prevenir fraude e cumprir obrigações legais.","Enviar novidades apenas quando houver consentimento opcional."]},
    {title:"Bases legais e transparência",paragraphs:["O tratamento poderá se apoiar na execução do contrato, cumprimento de obrigação legal, exercício regular de direitos, legítimo interesse após avaliação adequada e consentimento quando exigido. O consentimento para comunicações pode ser retirado a qualquer momento."]},
    {title:"Não comercialização e compartilhamento",paragraphs:["O Recomeçar não vende dados pessoais ou informações financeiras. Poderemos compartilhar o mínimo necessário com operadores de infraestrutura, autenticação, pagamentos, atendimento e análise, sempre sujeitos a deveres de segurança e confidencialidade."]},
    {title:"Segurança e retenção",paragraphs:["Adotamos medidas técnicas e administrativas proporcionais ao estágio do produto. Os dados serão conservados pelo período necessário às finalidades informadas, ao cumprimento de obrigações legais e ao exercício de direitos, e depois eliminados ou anonimizados quando aplicável."]},
    {title:"Seus direitos pela LGPD",items:["Confirmação da existência de tratamento e acesso aos dados.","Correção de dados incompletos, inexatos ou desatualizados.","Anonimização, bloqueio ou eliminação de dados desnecessários ou tratados em desconformidade.","Portabilidade, quando regulamentada e aplicável.","Informação sobre compartilhamentos e sobre a possibilidade de negar consentimento.","Revogação do consentimento e solicitação de eliminação dos dados tratados com consentimento, ressalvadas hipóteses legais de conservação.","Revisão de decisões unicamente automatizadas, quando aplicável."]},
    {title:"Como fazer uma solicitação",paragraphs:["Escreva para suporte@recomecar.app com o assunto “Privacidade e LGPD”. Poderemos solicitar informações para confirmar sua identidade antes de atender ao pedido. Você também pode peticionar à Autoridade Nacional de Proteção de Dados nas hipóteses previstas em lei."]},
  ]}/>;
}
