"use client";
import { useEffect,useState } from "react";
import { X } from "lucide-react";
import { Button,Input } from "./ui";
import { useDebts,type DebtRecord } from "@/lib/debts-storage";
export default function DebtModal({open,onClose,debt=null}:{open:boolean;onClose:()=>void;debt?:DebtRecord|null}){
  const{upsertDebt}=useDebts();const[name,setName]=useState("");const[type,setType]=useState("Cartão de crédito");const[total,setTotal]=useState("");const[paid,setPaid]=useState("");const[payment,setPayment]=useState("");const[rate,setRate]=useState("");
  useEffect(()=>{if(open){setName(debt?.name||"");setType(debt?.type||"Cartão de crédito");setTotal(debt?String(debt.total):"");setPaid(debt?String(debt.paid):"");setPayment(debt?String(debt.monthlyPayment):"");setRate(debt?String(debt.interestRate):"")}},[open,debt]);
  if(!open)return null;
  const submit=(e:React.FormEvent)=>{e.preventDefault();upsertDebt({name:name.trim(),type,total:Number(total),paid:Number(paid),monthlyPayment:Number(payment),interestRate:Number(rate)},debt?.id);onClose()};
  return <div className="fixed inset-0 z-[90] grid place-items-center bg-ink/45 p-4" role="dialog" aria-label={debt?"Editar dívida":"Nova dívida"}><form onSubmit={submit} className="w-full max-w-2xl rounded-[30px] bg-white p-7"><div className="flex justify-between"><div><p className="eyebrow">Dívidas</p><h2 className="mt-2 font-display text-4xl">{debt?"Editar dívida":"Nova dívida"}</h2></div><button type="button" onClick={onClose}><X/></button></div><div className="mt-7 grid gap-5 sm:grid-cols-2"><Input required label="Nome" value={name} onChange={e=>setName(e.target.value)}/><label className="grid gap-2 text-sm font-bold">Tipo<select value={type} onChange={e=>setType(e.target.value)} className="rounded-2xl border border-ink/10 px-4 py-3.5"><option>Cartão de crédito</option><option>Empréstimo</option><option>Financiamento</option><option>Parcelamento</option><option>Outro</option></select></label><Input required type="number" min="0.01" label="Valor total (R$)" value={total} onChange={e=>setTotal(e.target.value)}/><Input required type="number" min="0" label="Valor já pago (R$)" value={paid} onChange={e=>setPaid(e.target.value)}/><Input required type="number" min="0" label="Parcela mensal (R$)" value={payment} onChange={e=>setPayment(e.target.value)}/><Input type="number" min="0" step="0.01" label="Juros ao mês (%)" value={rate} onChange={e=>setRate(e.target.value)}/></div><div className="mt-7 flex justify-end gap-3"><Button type="button" variant="ghost" onClick={onClose}>Cancelar</Button><Button type="submit">Salvar dívida</Button></div></form></div>
}
