"use client";
import { useEffect,useState } from "react";
import { X } from "lucide-react";
import { Button,Input } from "./ui";
import { useGoals,type GoalRecord } from "@/lib/goals-storage";
export default function GoalModal({open,onClose,goal=null}:{open:boolean;onClose:()=>void;goal?:GoalRecord|null}){
 const{upsertGoal}=useGoals();const[name,setName]=useState("");const[category,setCategory]=useState("Reserva");const[target,setTarget]=useState("");const[current,setCurrent]=useState("");const[monthly,setMonthly]=useState("");const[date,setDate]=useState("");
 useEffect(()=>{if(open){setName(goal?.name||"");setCategory(goal?.category||"Reserva");setTarget(goal?String(goal.target):"");setCurrent(goal?String(goal.current):"");setMonthly(goal?String(goal.monthlyContribution):"");setDate(goal?.targetDate||"")}},[open,goal]);if(!open)return null;
 const submit=(e:React.FormEvent)=>{e.preventDefault();upsertGoal({name:name.trim(),category,target:Number(target),current:Number(current),monthlyContribution:Number(monthly),targetDate:date},goal?.id);onClose()};
 return <div className="fixed inset-0 z-[90] grid place-items-center bg-ink/45 p-4" role="dialog" aria-label={goal?"Editar meta":"Nova meta"}><form onSubmit={submit} className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-[30px] bg-white p-7"><div className="flex justify-between"><div><p className="eyebrow">Metas</p><h2 className="mt-2 font-display text-4xl">{goal?"Editar meta":"Nova meta"}</h2></div><button type="button" onClick={onClose}><X/></button></div><div className="mt-7 grid gap-5 sm:grid-cols-2"><Input required label="Nome da meta" value={name} onChange={e=>setName(e.target.value)}/><label className="grid gap-2 text-sm font-bold">Categoria<select value={category} onChange={e=>setCategory(e.target.value)} className="rounded-2xl border border-ink/10 px-4 py-3.5"><option>Reserva</option><option>Moradia</option><option>Viagem</option><option>Educação</option><option>Patrimônio</option><option>Compra</option><option>Outro</option></select></label><Input required type="number" min="0.01" label={category==="Patrimônio"?"Meta de patrimônio (R$)":"Valor alvo (R$)"} value={target} onChange={e=>setTarget(e.target.value)}/><Input required type="number" min="0" label={category==="Patrimônio"?"Patrimônio existente hoje (R$)":"Valor atual (R$)"} value={current} onChange={e=>setCurrent(e.target.value)}/><Input type="number" min="0" label="Contribuição mensal (R$)" value={monthly} onChange={e=>setMonthly(e.target.value)}/><Input type="date" label="Data desejada" value={date} onChange={e=>setDate(e.target.value)}/></div>{category==="Patrimônio"&&<p className="mt-4 rounded-2xl bg-mist p-4 text-sm leading-6 text-forest">O patrimônio existente atualizará imediatamente a Visão Geral e o progresso será calculado em relação à meta.</p>}<div className="mt-7 flex justify-end gap-3"><Button type="button" variant="ghost" onClick={onClose}>Cancelar</Button><Button type="submit">Salvar meta</Button></div></form></div>
}
